-- This file documents the core Landing -> Raw DML.
-- The same SQL is embedded in the task graph.

MERGE INTO BANKING_RAW.CORE.TRANSACTION_EVENT_RAW AS T
USING (
    SELECT
        PAYLOAD:eventId::VARCHAR                        AS EVENT_ID,
        PAYLOAD:transactionId::VARCHAR                  AS TRANSACTION_ID,
        UPPER(PAYLOAD:eventType::VARCHAR)               AS EVENT_TYPE,
        PAYLOAD:accountId::VARCHAR                      AS ACCOUNT_ID,
        PAYLOAD:counterpartyAccountId::VARCHAR          AS COUNTERPARTY_ACCOUNT_ID,
        TRY_TO_DECIMAL(PAYLOAD:amount::VARCHAR, 18, 2)  AS AMOUNT,
        UPPER(PAYLOAD:currency::VARCHAR)                AS CURRENCY,
        TRY_TO_TIMESTAMP_TZ(PAYLOAD:transactionTimestamp::VARCHAR) AS TRANSACTION_TS,
        COALESCE(TRY_TO_NUMBER(PAYLOAD:eventVersion::VARCHAR), 1) AS EVENT_VERSION,
        COALESCE(PAYLOAD:source::VARCHAR, 'BANKING_API') AS SOURCE_SYSTEM,
        SOURCE_FILE,
        SOURCE_ROW_NUMBER,
        PAYLOAD,
        LOAD_TS,
        ROW_NUMBER() OVER (
            PARTITION BY PAYLOAD:eventId::VARCHAR
            ORDER BY
                COALESCE(TRY_TO_NUMBER(PAYLOAD:eventVersion::VARCHAR), 1) DESC,
                LOAD_TS DESC
        ) AS RN
    FROM BANKING_LANDING.INGESTION.TRANSACTION_LANDING_STREAM
    WHERE PAYLOAD:eventId IS NOT NULL
      AND PAYLOAD:transactionId IS NOT NULL
      AND PAYLOAD:accountId IS NOT NULL
) AS S
ON T.EVENT_ID = S.EVENT_ID
WHEN MATCHED AND S.RN = 1 AND S.EVENT_VERSION >= T.EVENT_VERSION THEN
    UPDATE SET
        TRANSACTION_ID          = S.TRANSACTION_ID,
        EVENT_TYPE              = S.EVENT_TYPE,
        ACCOUNT_ID              = S.ACCOUNT_ID,
        COUNTERPARTY_ACCOUNT_ID = S.COUNTERPARTY_ACCOUNT_ID,
        AMOUNT                  = S.AMOUNT,
        CURRENCY                = S.CURRENCY,
        TRANSACTION_TS          = S.TRANSACTION_TS,
        EVENT_VERSION           = S.EVENT_VERSION,
        SOURCE_SYSTEM           = S.SOURCE_SYSTEM,
        SOURCE_FILE             = S.SOURCE_FILE,
        SOURCE_ROW_NUMBER       = S.SOURCE_ROW_NUMBER,
        ORIGINAL_PAYLOAD        = S.PAYLOAD,
        RAW_UPDATED_TS          = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND S.RN = 1 THEN
    INSERT (
        EVENT_ID, TRANSACTION_ID, EVENT_TYPE, ACCOUNT_ID,
        COUNTERPARTY_ACCOUNT_ID, AMOUNT, CURRENCY,
        TRANSACTION_TS, EVENT_VERSION, SOURCE_SYSTEM,
        SOURCE_FILE, SOURCE_ROW_NUMBER, ORIGINAL_PAYLOAD
    )
    VALUES (
        S.EVENT_ID, S.TRANSACTION_ID, S.EVENT_TYPE, S.ACCOUNT_ID,
        S.COUNTERPARTY_ACCOUNT_ID, S.AMOUNT, S.CURRENCY,
        S.TRANSACTION_TS, S.EVENT_VERSION, S.SOURCE_SYSTEM,
        S.SOURCE_FILE, S.SOURCE_ROW_NUMBER, S.PAYLOAD
    );
