USE DATABASE BANKING_LANDING;
USE SCHEMA INGESTION;

CREATE TABLE IF NOT EXISTS TRANSACTION_EVENT_LANDING (
    PAYLOAD             VARIANT         NOT NULL,
    SOURCE_FILE         VARCHAR         NOT NULL,
    SOURCE_ROW_NUMBER   NUMBER          NOT NULL,
    LOAD_TS             TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- Landing is insert-only, therefore append-only stream is sufficient.
CREATE OR REPLACE STREAM TRANSACTION_LANDING_STREAM
  ON TABLE TRANSACTION_EVENT_LANDING
  APPEND_ONLY = TRUE;
