-- 1. S3 visibility
LIST @BANKING_LANDING.INGESTION.TRANSACTION_S3_STAGE;

-- 2. Landing
SELECT
    SOURCE_FILE,
    COUNT(*) AS ROWS_LOADED,
    MIN(LOAD_TS) AS FIRST_LOAD_TS,
    MAX(LOAD_TS) AS LAST_LOAD_TS
FROM BANKING_LANDING.INGESTION.TRANSACTION_EVENT_LANDING
GROUP BY SOURCE_FILE
ORDER BY LAST_LOAD_TS DESC;

-- 3. RAW
SELECT *
FROM BANKING_RAW.CORE.TRANSACTION_EVENT_RAW
ORDER BY TRANSACTION_TS, EVENT_VERSION;

-- 4. Dimensions
SELECT *
FROM BANKING_PREPARED.CORE.DIM_ACCOUNT
ORDER BY ACCOUNT_KEY;

-- 5. Fact
SELECT *
FROM BANKING_PREPARED.CORE.FACT_TRANSACTION
ORDER BY TRANSACTION_TS;

-- 6. Bridge
SELECT *
FROM BANKING_PREPARED.CORE.BRIDGE_TRANSACTION_ACCOUNT
ORDER BY TRANSACTION_ID, ACCOUNT_ROLE;

-- 7. Curated history
SELECT *
FROM BANKING_CURATED.CORE.V_TRANSACTION_HISTORY
ORDER BY TRANSACTION_TS;

-- 8. Curated summary
SELECT *
FROM BANKING_CURATED.CORE.DAILY_TRANSACTION_SUMMARY
ORDER BY TRANSACTION_DATE, CURRENCY, EVENT_TYPE;

-- 9. Task status
SHOW TASKS IN SCHEMA BANKING_LANDING.PIPELINE;

-- 10. Recent task history
SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.TASK_HISTORY(
        SCHEDULED_TIME_RANGE_START => DATEADD('HOUR', -2, CURRENT_TIMESTAMP()),
        RESULT_LIMIT => 100
    )
)
ORDER BY SCHEDULED_TIME DESC;

-- 11. COPY history
SELECT *
FROM TABLE(
    BANKING_LANDING.INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'BANKING_LANDING.INGESTION.TRANSACTION_EVENT_LANDING',
        START_TIME => DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
    )
)
ORDER BY LAST_LOAD_TIME DESC;

-- 12. Reconciliation: landing vs distinct raw events.
SELECT
    (SELECT COUNT(*) FROM BANKING_LANDING.INGESTION.TRANSACTION_EVENT_LANDING) AS LANDING_ROWS,
    (SELECT COUNT(*) FROM BANKING_RAW.CORE.TRANSACTION_EVENT_RAW) AS RAW_EVENT_ROWS,
    (SELECT COUNT(*) FROM BANKING_PREPARED.CORE.FACT_TRANSACTION) AS PREPARED_TRANSACTION_ROWS;
