-- Data quality checks intended for CI/manual verification.

-- No null business keys in RAW.
SELECT *
FROM BANKING_RAW.CORE.TRANSACTION_EVENT_RAW
WHERE EVENT_ID IS NULL
   OR TRANSACTION_ID IS NULL
   OR ACCOUNT_ID IS NULL;

-- No invalid amount.
SELECT *
FROM BANKING_RAW.CORE.TRANSACTION_EVENT_RAW
WHERE AMOUNT IS NULL
   OR AMOUNT < 0;

-- ISO currency length check.
SELECT *
FROM BANKING_RAW.CORE.TRANSACTION_EVENT_RAW
WHERE LENGTH(CURRENCY) <> 3;

-- Duplicate EVENT_ID should return no rows.
SELECT EVENT_ID, COUNT(*) AS CNT
FROM BANKING_RAW.CORE.TRANSACTION_EVENT_RAW
GROUP BY EVENT_ID
HAVING COUNT(*) > 1;

-- Duplicate current transaction fact should return no rows.
SELECT TRANSACTION_ID, COUNT(*) AS CNT
FROM BANKING_PREPARED.CORE.FACT_TRANSACTION
GROUP BY TRANSACTION_ID
HAVING COUNT(*) > 1;

-- Fact rows should resolve their primary account dimension.
SELECT F.*
FROM BANKING_PREPARED.CORE.FACT_TRANSACTION F
LEFT JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT A
  ON A.ACCOUNT_KEY = F.ACCOUNT_KEY
WHERE A.ACCOUNT_KEY IS NULL;
