-- Execute as SECURITYADMIN / ACCOUNTADMIN in a trial account.

CREATE ROLE IF NOT EXISTS BANKING_PIPELINE_ROLE;
CREATE ROLE IF NOT EXISTS BANKING_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS BANKING_HIGH_CLEARANCE_ROLE;

GRANT USAGE ON WAREHOUSE BANKING_XS_WH TO ROLE BANKING_PIPELINE_ROLE;

GRANT USAGE ON DATABASE BANKING_LANDING TO ROLE BANKING_PIPELINE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BANKING_LANDING TO ROLE BANKING_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE BANKING_LANDING TO ROLE BANKING_PIPELINE_ROLE;
GRANT USAGE ON ALL STAGES IN DATABASE BANKING_LANDING TO ROLE BANKING_PIPELINE_ROLE;

GRANT USAGE ON DATABASE BANKING_RAW TO ROLE BANKING_PIPELINE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BANKING_RAW TO ROLE BANKING_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE BANKING_RAW TO ROLE BANKING_PIPELINE_ROLE;

GRANT USAGE ON DATABASE BANKING_PREPARED TO ROLE BANKING_PIPELINE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BANKING_PREPARED TO ROLE BANKING_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE BANKING_PREPARED TO ROLE BANKING_PIPELINE_ROLE;
GRANT USAGE ON ALL SEQUENCES IN DATABASE BANKING_PREPARED TO ROLE BANKING_PIPELINE_ROLE;

GRANT USAGE ON DATABASE BANKING_CURATED TO ROLE BANKING_PIPELINE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BANKING_CURATED TO ROLE BANKING_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE BANKING_CURATED TO ROLE BANKING_PIPELINE_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE BANKING_CURATED TO ROLE BANKING_PIPELINE_ROLE;

-- Consumer role: curated only.
GRANT USAGE ON WAREHOUSE BANKING_XS_WH TO ROLE BANKING_ANALYST_ROLE;
GRANT USAGE ON DATABASE BANKING_CURATED TO ROLE BANKING_ANALYST_ROLE;
GRANT USAGE ON SCHEMA BANKING_CURATED.CORE TO ROLE BANKING_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING_CURATED.CORE TO ROLE BANKING_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA BANKING_CURATED.CORE TO ROLE BANKING_ANALYST_ROLE;

-- Example masking policy pattern for future PII fields.
USE DATABASE BANKING_CURATED;
USE SCHEMA SECURE;

CREATE OR REPLACE MASKING POLICY MASK_STRING_PII AS (VAL STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('BANKING_HIGH_CLEARANCE_ROLE', 'ACCOUNTADMIN') THEN VAL
        ELSE '***MASKED***'
    END;

-- Example usage once a PII column exists:
-- ALTER TABLE <db>.<schema>.<table>
--   MODIFY COLUMN CUSTOMER_EMAIL
--   SET MASKING POLICY BANKING_CURATED.SECURE.MASK_STRING_PII;
