-- Run with a role that can create warehouses and databases, e.g. ACCOUNTADMIN for a trial account.

CREATE WAREHOUSE IF NOT EXISTS BANKING_XS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS BANKING_LANDING;
CREATE DATABASE IF NOT EXISTS BANKING_RAW;
CREATE DATABASE IF NOT EXISTS BANKING_PREPARED;
CREATE DATABASE IF NOT EXISTS BANKING_CURATED;

CREATE SCHEMA IF NOT EXISTS BANKING_LANDING.INGESTION;
CREATE SCHEMA IF NOT EXISTS BANKING_LANDING.PIPELINE;

CREATE SCHEMA IF NOT EXISTS BANKING_RAW.CORE;
CREATE SCHEMA IF NOT EXISTS BANKING_RAW.CDC;

CREATE SCHEMA IF NOT EXISTS BANKING_PREPARED.CORE;
CREATE SCHEMA IF NOT EXISTS BANKING_PREPARED.CDC;

CREATE SCHEMA IF NOT EXISTS BANKING_CURATED.CORE;
CREATE SCHEMA IF NOT EXISTS BANKING_CURATED.SECURE;
