USE DATABASE BANKING_PREPARED;
USE SCHEMA CORE;

CREATE SEQUENCE IF NOT EXISTS ACCOUNT_KEY_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS TRANSACTION_KEY_SEQ START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS DIM_ACCOUNT (
    ACCOUNT_KEY        NUMBER          NOT NULL DEFAULT ACCOUNT_KEY_SEQ.NEXTVAL,
    ACCOUNT_ID         VARCHAR         NOT NULL,
    CREATED_TS         TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TS         TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS FACT_TRANSACTION (
    TRANSACTION_KEY                NUMBER          NOT NULL DEFAULT TRANSACTION_KEY_SEQ.NEXTVAL,
    TRANSACTION_ID                 VARCHAR         NOT NULL,
    EVENT_ID                       VARCHAR         NOT NULL,
    ACCOUNT_KEY                    NUMBER          NOT NULL,
    COUNTERPARTY_ACCOUNT_KEY       NUMBER,
    EVENT_TYPE                     VARCHAR         NOT NULL,
    AMOUNT                         NUMBER(18,2)    NOT NULL,
    CURRENCY                       VARCHAR(3)      NOT NULL,
    TRANSACTION_TS                 TIMESTAMP_TZ    NOT NULL,
    TRANSACTION_DATE               DATE            NOT NULL,
    EVENT_VERSION                  NUMBER          NOT NULL,
    SOURCE_SYSTEM                  VARCHAR,
    PREPARED_CREATED_TS            TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PREPARED_UPDATED_TS            TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS BRIDGE_TRANSACTION_ACCOUNT (
    TRANSACTION_ID      VARCHAR         NOT NULL,
    ACCOUNT_KEY         NUMBER          NOT NULL,
    ACCOUNT_ROLE        VARCHAR         NOT NULL,
    CREATED_TS          TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TS          TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA BANKING_PREPARED.CDC;

CREATE OR REPLACE STREAM FACT_TRANSACTION_STREAM
  ON TABLE BANKING_PREPARED.CORE.FACT_TRANSACTION;
