-- Reference DML used by the task graph.

-- A) Maintain DIM_ACCOUNT using both primary and counterparty account IDs.

MERGE INTO BANKING_PREPARED.CORE.DIM_ACCOUNT T
USING (
    SELECT DISTINCT ACCOUNT_ID
    FROM (
        SELECT ACCOUNT_ID
        FROM BANKING_RAW.CDC.RAW_DIM_ACCOUNT_STREAM
        WHERE METADATA$ACTION = 'INSERT'
          AND ACCOUNT_ID IS NOT NULL

        UNION

        SELECT COUNTERPARTY_ACCOUNT_ID AS ACCOUNT_ID
        FROM BANKING_RAW.CDC.RAW_DIM_ACCOUNT_STREAM
        WHERE METADATA$ACTION = 'INSERT'
          AND COUNTERPARTY_ACCOUNT_ID IS NOT NULL
    )
) S
ON T.ACCOUNT_ID = S.ACCOUNT_ID
WHEN NOT MATCHED THEN
    INSERT (ACCOUNT_ID) VALUES (S.ACCOUNT_ID);


-- B) Maintain latest current-state transaction fact.
-- If several source events exist for one transaction, the highest version / latest timestamp wins.

MERGE INTO BANKING_PREPARED.CORE.FACT_TRANSACTION T
USING (
    SELECT
        R.TRANSACTION_ID,
        R.EVENT_ID,
        A.ACCOUNT_KEY,
        CA.ACCOUNT_KEY AS COUNTERPARTY_ACCOUNT_KEY,
        R.EVENT_TYPE,
        R.AMOUNT,
        R.CURRENCY,
        R.TRANSACTION_TS,
        TO_DATE(R.TRANSACTION_TS) AS TRANSACTION_DATE,
        R.EVENT_VERSION,
        R.SOURCE_SYSTEM
    FROM (
        SELECT *
        FROM BANKING_RAW.CDC.RAW_FACT_TRANSACTION_STREAM
        WHERE METADATA$ACTION = 'INSERT'
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY TRANSACTION_ID
            ORDER BY EVENT_VERSION DESC, TRANSACTION_TS DESC, RAW_UPDATED_TS DESC
        ) = 1
    ) R
    JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT A
      ON A.ACCOUNT_ID = R.ACCOUNT_ID
    LEFT JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT CA
      ON CA.ACCOUNT_ID = R.COUNTERPARTY_ACCOUNT_ID
) S
ON T.TRANSACTION_ID = S.TRANSACTION_ID
WHEN MATCHED AND S.EVENT_VERSION >= T.EVENT_VERSION THEN
    UPDATE SET
        EVENT_ID                 = S.EVENT_ID,
        ACCOUNT_KEY              = S.ACCOUNT_KEY,
        COUNTERPARTY_ACCOUNT_KEY = S.COUNTERPARTY_ACCOUNT_KEY,
        EVENT_TYPE               = S.EVENT_TYPE,
        AMOUNT                   = S.AMOUNT,
        CURRENCY                 = S.CURRENCY,
        TRANSACTION_TS           = S.TRANSACTION_TS,
        TRANSACTION_DATE         = S.TRANSACTION_DATE,
        EVENT_VERSION            = S.EVENT_VERSION,
        SOURCE_SYSTEM            = S.SOURCE_SYSTEM,
        PREPARED_UPDATED_TS      = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        TRANSACTION_ID, EVENT_ID, ACCOUNT_KEY, COUNTERPARTY_ACCOUNT_KEY,
        EVENT_TYPE, AMOUNT, CURRENCY, TRANSACTION_TS, TRANSACTION_DATE,
        EVENT_VERSION, SOURCE_SYSTEM
    )
    VALUES (
        S.TRANSACTION_ID, S.EVENT_ID, S.ACCOUNT_KEY, S.COUNTERPARTY_ACCOUNT_KEY,
        S.EVENT_TYPE, S.AMOUNT, S.CURRENCY, S.TRANSACTION_TS, S.TRANSACTION_DATE,
        S.EVENT_VERSION, S.SOURCE_SYSTEM
    );


-- C) Maintain transaction/account bridge.

MERGE INTO BANKING_PREPARED.CORE.BRIDGE_TRANSACTION_ACCOUNT T
USING (
    SELECT DISTINCT
        R.TRANSACTION_ID,
        A.ACCOUNT_KEY,
        'PRIMARY' AS ACCOUNT_ROLE
    FROM BANKING_RAW.CDC.RAW_BRIDGE_STREAM R
    JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT A
      ON A.ACCOUNT_ID = R.ACCOUNT_ID
    WHERE METADATA$ACTION = 'INSERT'

    UNION

    SELECT DISTINCT
        R.TRANSACTION_ID,
        A.ACCOUNT_KEY,
        'COUNTERPARTY' AS ACCOUNT_ROLE
    FROM BANKING_RAW.CDC.RAW_BRIDGE_STREAM R
    JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT A
      ON A.ACCOUNT_ID = R.COUNTERPARTY_ACCOUNT_ID
    WHERE METADATA$ACTION = 'INSERT'
      AND R.COUNTERPARTY_ACCOUNT_ID IS NOT NULL
) S
ON T.TRANSACTION_ID = S.TRANSACTION_ID
AND T.ACCOUNT_KEY = S.ACCOUNT_KEY
AND T.ACCOUNT_ROLE = S.ACCOUNT_ROLE
WHEN NOT MATCHED THEN
    INSERT (TRANSACTION_ID, ACCOUNT_KEY, ACCOUNT_ROLE)
    VALUES (S.TRANSACTION_ID, S.ACCOUNT_KEY, S.ACCOUNT_ROLE);
