USE DATABASE BANKING_LANDING;
USE SCHEMA INGESTION;

CREATE OR REPLACE FILE FORMAT TRANSACTION_NDJSON_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE
  COMPRESSION = AUTO;

-- Replace the bucket placeholder.
CREATE OR REPLACE STAGE TRANSACTION_S3_STAGE
  URL = 's3://<YOUR_S3_BUCKET>/banking-transactions/'
  STORAGE_INTEGRATION = BANKING_S3_INT
  FILE_FORMAT = TRANSACTION_NDJSON_FORMAT;

-- Optional smoke test:
LIST @TRANSACTION_S3_STAGE;
