USE DATABASE BANKING_CURATED;
USE SCHEMA CORE;

CREATE OR REPLACE VIEW V_TRANSACTION_HISTORY AS
SELECT
    F.TRANSACTION_ID,
    F.EVENT_ID,
    A.ACCOUNT_ID,
    CA.ACCOUNT_ID AS COUNTERPARTY_ACCOUNT_ID,
    F.EVENT_TYPE,
    F.AMOUNT,
    F.CURRENCY,
    F.TRANSACTION_TS,
    F.EVENT_VERSION,
    F.SOURCE_SYSTEM
FROM BANKING_PREPARED.CORE.FACT_TRANSACTION F
JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT A
  ON A.ACCOUNT_KEY = F.ACCOUNT_KEY
LEFT JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT CA
  ON CA.ACCOUNT_KEY = F.COUNTERPARTY_ACCOUNT_KEY;

CREATE TABLE IF NOT EXISTS DAILY_TRANSACTION_SUMMARY (
    TRANSACTION_DATE     DATE            NOT NULL,
    CURRENCY             VARCHAR(3)      NOT NULL,
    EVENT_TYPE           VARCHAR         NOT NULL,
    TRANSACTION_COUNT    NUMBER          NOT NULL,
    TOTAL_AMOUNT         NUMBER(20,2)    NOT NULL,
    LAST_REFRESH_TS      TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
