-- Recompute only business keys/dates touched by the FACT stream.

MERGE INTO BANKING_CURATED.CORE.DAILY_TRANSACTION_SUMMARY T
USING (
    WITH AFFECTED_KEYS AS (
        SELECT DISTINCT
            TRANSACTION_DATE,
            CURRENCY,
            EVENT_TYPE
        FROM BANKING_PREPARED.CDC.FACT_TRANSACTION_STREAM
    )
    SELECT
        F.TRANSACTION_DATE,
        F.CURRENCY,
        F.EVENT_TYPE,
        COUNT(*) AS TRANSACTION_COUNT,
        SUM(F.AMOUNT) AS TOTAL_AMOUNT
    FROM BANKING_PREPARED.CORE.FACT_TRANSACTION F
    JOIN AFFECTED_KEYS K
      ON K.TRANSACTION_DATE = F.TRANSACTION_DATE
     AND K.CURRENCY = F.CURRENCY
     AND K.EVENT_TYPE = F.EVENT_TYPE
    GROUP BY F.TRANSACTION_DATE, F.CURRENCY, F.EVENT_TYPE
) S
ON T.TRANSACTION_DATE = S.TRANSACTION_DATE
AND T.CURRENCY = S.CURRENCY
AND T.EVENT_TYPE = S.EVENT_TYPE
WHEN MATCHED THEN
    UPDATE SET
        TRANSACTION_COUNT = S.TRANSACTION_COUNT,
        TOTAL_AMOUNT      = S.TOTAL_AMOUNT,
        LAST_REFRESH_TS   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        TRANSACTION_DATE, CURRENCY, EVENT_TYPE,
        TRANSACTION_COUNT, TOTAL_AMOUNT
    )
    VALUES (
        S.TRANSACTION_DATE, S.CURRENCY, S.EVENT_TYPE,
        S.TRANSACTION_COUNT, S.TOTAL_AMOUNT
    );
