-- Run after all base objects exist.
-- Tasks are created suspended by default.

-- Root: S3 -> Landing
CREATE OR REPLACE TASK BANKING_LANDING.PIPELINE.LOAD_LANDING_TASK
  WAREHOUSE = BANKING_XS_WH
  SCHEDULE = '1 MINUTE'
AS
COPY INTO BANKING_LANDING.INGESTION.TRANSACTION_EVENT_LANDING
    (PAYLOAD, SOURCE_FILE, SOURCE_ROW_NUMBER, LOAD_TS)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        CURRENT_TIMESTAMP()
    FROM @BANKING_LANDING.INGESTION.TRANSACTION_S3_STAGE
)
FILE_FORMAT = (FORMAT_NAME = BANKING_LANDING.INGESTION.TRANSACTION_NDJSON_FORMAT)
ON_ERROR = 'CONTINUE';


-- Landing -> Raw
CREATE OR REPLACE TASK BANKING_LANDING.PIPELINE.LANDING_TO_RAW_TASK
  WAREHOUSE = BANKING_XS_WH
  AFTER BANKING_LANDING.PIPELINE.LOAD_LANDING_TASK
  WHEN SYSTEM$STREAM_HAS_DATA('BANKING_LANDING.INGESTION.TRANSACTION_LANDING_STREAM')
AS
MERGE INTO BANKING_RAW.CORE.TRANSACTION_EVENT_RAW AS T
USING (
    SELECT
        PAYLOAD:eventId::VARCHAR                        AS EVENT_ID,
        PAYLOAD:transactionId::VARCHAR                  AS TRANSACTION_ID,
        UPPER(PAYLOAD:eventType::VARCHAR)               AS EVENT_TYPE,
        PAYLOAD:accountId::VARCHAR                      AS ACCOUNT_ID,
        PAYLOAD:counterpartyAccountId::VARCHAR          AS COUNTERPARTY_ACCOUNT_ID,
        TRY_TO_DECIMAL(PAYLOAD:amount::VARCHAR, 18, 2)  AS AMOUNT,
        UPPER(PAYLOAD:currency::VARCHAR)                AS CURRENCY,
        TRY_TO_TIMESTAMP_TZ(PAYLOAD:transactionTimestamp::VARCHAR) AS TRANSACTION_TS,
        COALESCE(TRY_TO_NUMBER(PAYLOAD:eventVersion::VARCHAR), 1) AS EVENT_VERSION,
        COALESCE(PAYLOAD:source::VARCHAR, 'BANKING_API') AS SOURCE_SYSTEM,
        SOURCE_FILE,
        SOURCE_ROW_NUMBER,
        PAYLOAD,
        LOAD_TS,
        ROW_NUMBER() OVER (
            PARTITION BY PAYLOAD:eventId::VARCHAR
            ORDER BY
                COALESCE(TRY_TO_NUMBER(PAYLOAD:eventVersion::VARCHAR), 1) DESC,
                LOAD_TS DESC
        ) AS RN
    FROM BANKING_LANDING.INGESTION.TRANSACTION_LANDING_STREAM
    WHERE PAYLOAD:eventId IS NOT NULL
      AND PAYLOAD:transactionId IS NOT NULL
      AND PAYLOAD:accountId IS NOT NULL
) AS S
ON T.EVENT_ID = S.EVENT_ID
WHEN MATCHED AND S.RN = 1 AND S.EVENT_VERSION >= T.EVENT_VERSION THEN
    UPDATE SET
        TRANSACTION_ID          = S.TRANSACTION_ID,
        EVENT_TYPE              = S.EVENT_TYPE,
        ACCOUNT_ID              = S.ACCOUNT_ID,
        COUNTERPARTY_ACCOUNT_ID = S.COUNTERPARTY_ACCOUNT_ID,
        AMOUNT                  = S.AMOUNT,
        CURRENCY                = S.CURRENCY,
        TRANSACTION_TS          = S.TRANSACTION_TS,
        EVENT_VERSION           = S.EVENT_VERSION,
        SOURCE_SYSTEM           = S.SOURCE_SYSTEM,
        SOURCE_FILE             = S.SOURCE_FILE,
        SOURCE_ROW_NUMBER       = S.SOURCE_ROW_NUMBER,
        ORIGINAL_PAYLOAD        = S.PAYLOAD,
        RAW_UPDATED_TS          = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND S.RN = 1 THEN
    INSERT (
        EVENT_ID, TRANSACTION_ID, EVENT_TYPE, ACCOUNT_ID,
        COUNTERPARTY_ACCOUNT_ID, AMOUNT, CURRENCY,
        TRANSACTION_TS, EVENT_VERSION, SOURCE_SYSTEM,
        SOURCE_FILE, SOURCE_ROW_NUMBER, ORIGINAL_PAYLOAD
    )
    VALUES (
        S.EVENT_ID, S.TRANSACTION_ID, S.EVENT_TYPE, S.ACCOUNT_ID,
        S.COUNTERPARTY_ACCOUNT_ID, S.AMOUNT, S.CURRENCY,
        S.TRANSACTION_TS, S.EVENT_VERSION, S.SOURCE_SYSTEM,
        S.SOURCE_FILE, S.SOURCE_ROW_NUMBER, S.PAYLOAD
    );


-- Raw -> Account dimension
CREATE OR REPLACE TASK BANKING_LANDING.PIPELINE.RAW_TO_DIM_ACCOUNT_TASK
  WAREHOUSE = BANKING_XS_WH
  AFTER BANKING_LANDING.PIPELINE.LANDING_TO_RAW_TASK
  WHEN SYSTEM$STREAM_HAS_DATA('BANKING_RAW.CDC.RAW_DIM_ACCOUNT_STREAM')
AS
MERGE INTO BANKING_PREPARED.CORE.DIM_ACCOUNT T
USING (
    SELECT DISTINCT ACCOUNT_ID
    FROM (
        SELECT ACCOUNT_ID
        FROM BANKING_RAW.CDC.RAW_DIM_ACCOUNT_STREAM
        WHERE METADATA$ACTION = 'INSERT'
          AND ACCOUNT_ID IS NOT NULL
        UNION
        SELECT COUNTERPARTY_ACCOUNT_ID AS ACCOUNT_ID
        FROM BANKING_RAW.CDC.RAW_DIM_ACCOUNT_STREAM
        WHERE METADATA$ACTION = 'INSERT'
          AND COUNTERPARTY_ACCOUNT_ID IS NOT NULL
    )
) S
ON T.ACCOUNT_ID = S.ACCOUNT_ID
WHEN NOT MATCHED THEN
    INSERT (ACCOUNT_ID) VALUES (S.ACCOUNT_ID);


-- Raw -> Fact
CREATE OR REPLACE TASK BANKING_LANDING.PIPELINE.RAW_TO_FACT_TRANSACTION_TASK
  WAREHOUSE = BANKING_XS_WH
  AFTER BANKING_LANDING.PIPELINE.RAW_TO_DIM_ACCOUNT_TASK
  WHEN SYSTEM$STREAM_HAS_DATA('BANKING_RAW.CDC.RAW_FACT_TRANSACTION_STREAM')
AS
MERGE INTO BANKING_PREPARED.CORE.FACT_TRANSACTION T
USING (
    SELECT
        R.TRANSACTION_ID,
        R.EVENT_ID,
        A.ACCOUNT_KEY,
        CA.ACCOUNT_KEY AS COUNTERPARTY_ACCOUNT_KEY,
        R.EVENT_TYPE,
        R.AMOUNT,
        R.CURRENCY,
        R.TRANSACTION_TS,
        TO_DATE(R.TRANSACTION_TS) AS TRANSACTION_DATE,
        R.EVENT_VERSION,
        R.SOURCE_SYSTEM
    FROM (
        SELECT *
        FROM BANKING_RAW.CDC.RAW_FACT_TRANSACTION_STREAM
        WHERE METADATA$ACTION = 'INSERT'
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY TRANSACTION_ID
            ORDER BY EVENT_VERSION DESC, TRANSACTION_TS DESC, RAW_UPDATED_TS DESC
        ) = 1
    ) R
    JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT A
      ON A.ACCOUNT_ID = R.ACCOUNT_ID
    LEFT JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT CA
      ON CA.ACCOUNT_ID = R.COUNTERPARTY_ACCOUNT_ID
) S
ON T.TRANSACTION_ID = S.TRANSACTION_ID
WHEN MATCHED AND S.EVENT_VERSION >= T.EVENT_VERSION THEN
    UPDATE SET
        EVENT_ID                 = S.EVENT_ID,
        ACCOUNT_KEY              = S.ACCOUNT_KEY,
        COUNTERPARTY_ACCOUNT_KEY = S.COUNTERPARTY_ACCOUNT_KEY,
        EVENT_TYPE               = S.EVENT_TYPE,
        AMOUNT                   = S.AMOUNT,
        CURRENCY                 = S.CURRENCY,
        TRANSACTION_TS           = S.TRANSACTION_TS,
        TRANSACTION_DATE         = S.TRANSACTION_DATE,
        EVENT_VERSION            = S.EVENT_VERSION,
        SOURCE_SYSTEM            = S.SOURCE_SYSTEM,
        PREPARED_UPDATED_TS      = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        TRANSACTION_ID, EVENT_ID, ACCOUNT_KEY, COUNTERPARTY_ACCOUNT_KEY,
        EVENT_TYPE, AMOUNT, CURRENCY, TRANSACTION_TS, TRANSACTION_DATE,
        EVENT_VERSION, SOURCE_SYSTEM
    )
    VALUES (
        S.TRANSACTION_ID, S.EVENT_ID, S.ACCOUNT_KEY, S.COUNTERPARTY_ACCOUNT_KEY,
        S.EVENT_TYPE, S.AMOUNT, S.CURRENCY, S.TRANSACTION_TS, S.TRANSACTION_DATE,
        S.EVENT_VERSION, S.SOURCE_SYSTEM
    );


-- Raw -> Bridge
CREATE OR REPLACE TASK BANKING_LANDING.PIPELINE.RAW_TO_BRIDGE_TASK
  WAREHOUSE = BANKING_XS_WH
  AFTER BANKING_LANDING.PIPELINE.RAW_TO_FACT_TRANSACTION_TASK
  WHEN SYSTEM$STREAM_HAS_DATA('BANKING_RAW.CDC.RAW_BRIDGE_STREAM')
AS
MERGE INTO BANKING_PREPARED.CORE.BRIDGE_TRANSACTION_ACCOUNT T
USING (
    SELECT DISTINCT
        R.TRANSACTION_ID,
        A.ACCOUNT_KEY,
        'PRIMARY' AS ACCOUNT_ROLE
    FROM BANKING_RAW.CDC.RAW_BRIDGE_STREAM R
    JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT A
      ON A.ACCOUNT_ID = R.ACCOUNT_ID
    WHERE METADATA$ACTION = 'INSERT'

    UNION

    SELECT DISTINCT
        R.TRANSACTION_ID,
        A.ACCOUNT_KEY,
        'COUNTERPARTY' AS ACCOUNT_ROLE
    FROM BANKING_RAW.CDC.RAW_BRIDGE_STREAM R
    JOIN BANKING_PREPARED.CORE.DIM_ACCOUNT A
      ON A.ACCOUNT_ID = R.COUNTERPARTY_ACCOUNT_ID
    WHERE METADATA$ACTION = 'INSERT'
      AND R.COUNTERPARTY_ACCOUNT_ID IS NOT NULL
) S
ON T.TRANSACTION_ID = S.TRANSACTION_ID
AND T.ACCOUNT_KEY = S.ACCOUNT_KEY
AND T.ACCOUNT_ROLE = S.ACCOUNT_ROLE
WHEN NOT MATCHED THEN
    INSERT (TRANSACTION_ID, ACCOUNT_KEY, ACCOUNT_ROLE)
    VALUES (S.TRANSACTION_ID, S.ACCOUNT_KEY, S.ACCOUNT_ROLE);


-- Prepared -> Curated aggregate
CREATE OR REPLACE TASK BANKING_LANDING.PIPELINE.PREPARED_TO_CURATED_TASK
  WAREHOUSE = BANKING_XS_WH
  AFTER BANKING_LANDING.PIPELINE.RAW_TO_BRIDGE_TASK
  WHEN SYSTEM$STREAM_HAS_DATA('BANKING_PREPARED.CDC.FACT_TRANSACTION_STREAM')
AS
MERGE INTO BANKING_CURATED.CORE.DAILY_TRANSACTION_SUMMARY T
USING (
    WITH AFFECTED_KEYS AS (
        SELECT DISTINCT
            TRANSACTION_DATE,
            CURRENCY,
            EVENT_TYPE
        FROM BANKING_PREPARED.CDC.FACT_TRANSACTION_STREAM
    )
    SELECT
        F.TRANSACTION_DATE,
        F.CURRENCY,
        F.EVENT_TYPE,
        COUNT(*) AS TRANSACTION_COUNT,
        SUM(F.AMOUNT) AS TOTAL_AMOUNT
    FROM BANKING_PREPARED.CORE.FACT_TRANSACTION F
    JOIN AFFECTED_KEYS K
      ON K.TRANSACTION_DATE = F.TRANSACTION_DATE
     AND K.CURRENCY = F.CURRENCY
     AND K.EVENT_TYPE = F.EVENT_TYPE
    GROUP BY F.TRANSACTION_DATE, F.CURRENCY, F.EVENT_TYPE
) S
ON T.TRANSACTION_DATE = S.TRANSACTION_DATE
AND T.CURRENCY = S.CURRENCY
AND T.EVENT_TYPE = S.EVENT_TYPE
WHEN MATCHED THEN
    UPDATE SET
        TRANSACTION_COUNT = S.TRANSACTION_COUNT,
        TOTAL_AMOUNT      = S.TOTAL_AMOUNT,
        LAST_REFRESH_TS   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        TRANSACTION_DATE, CURRENCY, EVENT_TYPE,
        TRANSACTION_COUNT, TOTAL_AMOUNT
    )
    VALUES (
        S.TRANSACTION_DATE, S.CURRENCY, S.EVENT_TYPE,
        S.TRANSACTION_COUNT, S.TOTAL_AMOUNT
    );
