-- Resume children first, root last.

ALTER TASK BANKING_LANDING.PIPELINE.PREPARED_TO_CURATED_TASK RESUME;
ALTER TASK BANKING_LANDING.PIPELINE.RAW_TO_BRIDGE_TASK RESUME;
ALTER TASK BANKING_LANDING.PIPELINE.RAW_TO_FACT_TRANSACTION_TASK RESUME;
ALTER TASK BANKING_LANDING.PIPELINE.RAW_TO_DIM_ACCOUNT_TASK RESUME;
ALTER TASK BANKING_LANDING.PIPELINE.LANDING_TO_RAW_TASK RESUME;
ALTER TASK BANKING_LANDING.PIPELINE.LOAD_LANDING_TASK RESUME;

SHOW TASKS IN SCHEMA BANKING_LANDING.PIPELINE;
