-- Suspend the root first to stop new graph runs, then suspend children.

ALTER TASK BANKING_LANDING.PIPELINE.LOAD_LANDING_TASK SUSPEND;
ALTER TASK BANKING_LANDING.PIPELINE.LANDING_TO_RAW_TASK SUSPEND;
ALTER TASK BANKING_LANDING.PIPELINE.RAW_TO_DIM_ACCOUNT_TASK SUSPEND;
ALTER TASK BANKING_LANDING.PIPELINE.RAW_TO_FACT_TRANSACTION_TASK SUSPEND;
ALTER TASK BANKING_LANDING.PIPELINE.RAW_TO_BRIDGE_TASK SUSPEND;
ALTER TASK BANKING_LANDING.PIPELINE.PREPARED_TO_CURATED_TASK SUSPEND;
